service: docebo-lms-api-proxy

provider:
  name: aws
  runtime: nodejs22.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, 'us-east-1'}
  environment:
    DOCEBO_BASE_URL: ${env:DOCEBO_BASE_URL}
    DOCEBO_ACCESS_TOKEN: ${env:DOCEBO_ACCESS_TOKEN}

functions:
  app:
    handler: src/lambda.handler
    events:
      - http:
          path: /
          method: ANY
          cors: true
      - http:
          path: /{proxy+}
          method: ANY
          cors: true

plugins:
  - serverless-offline

custom:
  serverless-offline:
    httpPort: 3000